### ISSUE TITLE
Integrate Auto Library

### ISSUE THREAD

**Issue by bhavinshah7** [graph-quilt/graphql-authorization-java#18]
Integrate [Auto Library](https://github.com/intuit/auto) with orchestrator to achieve the following:

* Calculate semantic version bumps from PRs
* Skip a release with the skip-release label
* Generate changelogs with headers, authors
* Use labels to create new changelog sections
* Generate a GitHub release

**Comment by bharath2203** [comment]
Hi, @bhavinshah7 I would like to work on this issue. Is it possible to assign the issue to me?
Thanks

**Comment by bhavinshah7** [comment]
@bharath2203  you will need this info while setting up Auto:
Owner/ServiceAccount: https://github.com/graphquilt-svc
email: graphquilt@gmail.com
I am giving you push access, so you can create a personal github token to set up Auto.

You might want to look at [this Github action](https://github.com/auto-it/setup-auto) to add auto to one of the [workflows](https://github.com/graph-quilt/graphql-authorization-java/tree/master/.github/workflows)

**Comment by bharath2203** [comment]
Thanks for the guidance @bhavinshah7 
I will start working on this.
