### ISSUE TITLE
Use this library in a sample graphql app

### ISSUE THREAD

**Issue by ashpak-shaikh** [graph-quilt/graphql-authorization-java#34]
* Try out the AuthzInstrumentation in your app or the sample app in this github org
* Update the readme and github pages documentation.

**Comment by GayathriMuthukrishnan** [comment]
I am interested in taking up this issue. Could you assign it to me.

**Comment by tasneemkoushar** [comment]
@ashpak-shaikh I am interested on this issue, can I take this one?
