### ISSUE TITLE
Enhance the library to enable custom error message.

### ISSUE THREAD

**Issue by ashpak-shaikh** [graph-quilt/graphql-authorization-java#39]
The interface [scope provider](https://github.com/graph-quilt/graphql-authorization-java/blob/master/src/main/java/com/intuit/graphql/authorization/util/ScopeProvider.java#L6) can add a new method to that takes in the required details and return a customized message 

``` String createErrorMessage(RedactionContext redactionContext);```

**Comment by patelhumaira21** [comment]
I can take this
